title: OLUWATOSIN OLUWASEUN MULERO
logo: TOSIN.png
description: Data analyst with two years experience, highly skilled with the use of Microsoft Excel, SQL and PowerBI
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
